### PR TITLE
[WIP] Implement create flow

### PR DESCRIPTION
**Pull request by danillouz**
This isn't ready yet, but I thought this to be easiest in terms of discussing implementation, since here we also get the deployment preview.

For now there's a very basic create flow which you can try out. I'm still working on the best way to implement it, but maybe you can think a bit about the UI/UX.

As for the implementation these are some questions/TODOs for me, but feel free to help out if you like 🙂:
- [x] Whats the best way to structure the reducer(s). I.e. fetch, update, create, delete.
- [x] Should the page components be grouped differently? `<StatusCreate/>` and `<StatusDetails/>` are like sub pages of `<Statuses/>` (also in terms of data flow). Maybe grouping them in a subdir would make sense, but since there's only one route (`/statuses`) might be overkill for now.
- [x] Should there be a dedicated API layer which makes the requests?
- [x] Should component action state be part of the component or reducer? For example, fetching, error, created, etc.
- [x] Naming: statuses, applications or something else?

### CODE REVIEW

**Comment by dinostheo** [comment]
The form seems fine 💯. 

The `status` or `statuses` as the description does not make sense. 
`applications` comes closer. I was thinking that an accurate description of the data we have is `vacancy` --> `vacancies`, but I also don't like how this word sounds.

**Comment by danillouz** [comment]
I hooked up all side effect related code to call the (mock) API. Reading, creating and updating now resemble the "real thing" more.
Since the mock fetch has a timeout to simulate a HTTP req, I also added feedback in the UI, i.e. fetching, updating and creating. This brings up the question if we'd like to do "optimistic creates/updates/deletes".

Besides that I'm still thinking about what proper abstractions and separation of concerns are in terms of structuring components and passing data/behavior between them. But getting that right is quite tricky 🙂, especially since I haven't been working a lot with React.
I'm trying to structure the pages/components in a way that makes sense hierarchically/structurally. As well as trying to make it easy to understand how the data flows. I'm curious if it makes sense to you @dinostheo and if you have any suggestions.

I'm also a bit out of my depth when it comes to testing with React, so for now I'm just testing non-react stuff 😅 where possible.

**Comment by danillouz** [comment]
Rebased on master.

**Comment by danillouz** [comment]
OK, that appears to be a good sign! Do you have another suggestion for the naming?

The `pages` name is something I saw other engineers do when building larger React apps. However this was a while back, so I don't know if there are other conventions or "better ways" now.

Without going into the semantics of the true meaning of a SPA 😂, the `pages` dir is meant to group route aware components that are "smart". These type of components are sometimes also referred to as "smart components" (a.k.a container components). What distinguishes them from the so called "dumb components" is that they handle side effects (like making API calls to fetch data) and delegate/pass behavior/information to their children, which are dumb 🙊.

Currently the structure is still in limbo, meaning it's somewhere in between the structure of a small and larger app. As the application would grow and introduce more domains it would be best to also group it by domain (instead of behavior). So the reducer and other domain specific logic would be part of the `Statuses` module (or other domain name), i.e. `src/pages/Statuses/`. But I believe grouping by domain already would complicate things.

Since we're still experimenting and trying to get a better understanding of the domain and requirements, I change things in small steps (sometimes back and forth). I do this to see how certain functionality affects the composition of components and what the simplest way could be to hook them up.

For now, if it's understandable and easy to change, I think that's good enough, because them we can make progress. But ultimately this "research" should help layer the architecture in order to help establish a simple mental model (and improve "ilities").

**Pull request merged**
